#include <stdio.h>
#include <stdlib.h>
#include "../lexer/lexer.h"
#include "../parser/parser.h"
#include "../emitter/ast_to_ir.h"
#include "../ir/ir.h"
#include "../../vm/bytecode/bytecode.h"
#include "../emitter/ir_to_bytecode.h"

int main() {
    printf("=== He³ Method/Function Translation Test ===\n\n");
    
    // Test source code with method calls and function definitions
    const char* source = 
        "domain app.main;\n"
        "class Program {\n"
        "  function main(): integer {\n"
        "    var x: integer = 5;\n"
        "    var y: integer = add(x, 3);\n"
        "    var result: integer = x.add(2);\n"
        "    return y + result;\n"
        "  }\n"
        "  \n"
        "  function add(a: integer, b: integer): integer {\n"
        "    return a + b;\n"
        "  }\n"
        "}\n";
    
    printf("Source code:\n%s\n", source);
    
    // Create lexer
    Lexer* lexer = lexer_create(source);
    if (!lexer) {
        printf("Failed to create lexer\n");
        return 1;
    }
    
    // Create parser
    Parser* parser = parser_create(lexer);
    if (!parser) {
        printf("Failed to create parser\n");
        lexer_destroy(lexer);
        return 1;
    }
    
    // Parse source
    printf("=== Parsing Source ===\n");
    Ast* ast = parse_compilation_unit(parser);
    if (!ast) {
        printf("Failed to parse source\n");
        parser_destroy(parser);
        lexer_destroy(lexer);
        return 1;
    }
    
    printf("Parse successful!\n");
    
    // Print AST
    printf("\n=== Generated AST ===\n");
    ast_print_tree(ast, 0);
    
    // Create AST to IR translator
    AstToIRTranslator* translator = ast_to_ir_translator_create();
    if (!translator) {
        printf("Failed to create AST to IR translator\n");
        ast_destroy_tree(ast);
        parser_destroy(parser);
        lexer_destroy(lexer);
        return 1;
    }
    
    // Translate AST to IR
    printf("\n=== Translating AST to IR ===\n");
    IRFunction* ir_function = ast_to_ir_translate_compilation_unit(translator, ast);
    if (!ir_function) {
        printf("Translation failed: %s\n", ast_to_ir_translator_get_error(translator));
        ast_to_ir_translator_destroy(translator);
        ast_destroy_tree(ast);
        parser_destroy(parser);
        lexer_destroy(lexer);
        return 1;
    }
    
    printf("Translation successful!\n");
    
    // Print IR
    printf("\n=== Generated IR ===\n");
    ir_print_function(ir_function);
    
    // Create bytecode writer
    BytecodeWriter* writer = bytecode_writer_create(1024);
    if (!writer) {
        printf("Failed to create bytecode writer\n");
        ast_to_ir_translator_destroy(translator);
        ast_destroy_tree(ast);
        parser_destroy(parser);
        lexer_destroy(lexer);
        return 1;
    }
    
    // Create IR to bytecode translator
    IRToBytecodeTranslator* ir_translator = ir_to_bytecode_translator_create(writer);
    if (!ir_translator) {
        printf("Failed to create IR to bytecode translator\n");
        bytecode_writer_destroy(writer);
        ast_to_ir_translator_destroy(translator);
        ast_destroy_tree(ast);
        parser_destroy(parser);
        lexer_destroy(lexer);
        return 1;
    }
    
    // Translate IR to bytecode
    printf("\n=== Translating IR to Bytecode ===\n");
    if (!ir_to_bytecode_translate_function(ir_translator, ir_function)) {
        printf("IR to bytecode translation failed: %s\n", ir_to_bytecode_translator_get_error(ir_translator));
        ir_to_bytecode_translator_destroy(ir_translator);
        bytecode_writer_destroy(writer);
        ast_to_ir_translator_destroy(translator);
        ast_destroy_tree(ast);
        parser_destroy(parser);
        lexer_destroy(lexer);
        return 1;
    }
    
    printf("IR to bytecode translation successful!\n");
    
    // Print bytecode
    printf("\n=== Generated Bytecode ===\n");
    bytecode_writer_print_disassembly(writer);
    
    // Print hex dump
    printf("\n=== Hex Dump ===\n");
    bytecode_writer_print_hex(writer);
    
    // Clean up
    ir_to_bytecode_translator_destroy(ir_translator);
    bytecode_writer_destroy(writer);
    ast_to_ir_translator_destroy(translator);
    ast_destroy_tree(ast);
    parser_destroy(parser);
    lexer_destroy(lexer);
    
    printf("\n=== Test Complete ===\n");
    return 0;
}
