#!/bin/bash

# He³ Examples Test Script
# This script tests the compilation of example files

echo "He³ Examples Test Script"
echo "========================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Test function
test_example() {
    local file=$1
    local name=$2
    
    echo -n "Testing $name... "
    
    if [ ! -f "$file" ]; then
        echo -e "${RED}FAIL${NC} - File not found: $file"
        return 1
    fi
    
    # For now, just check if the file exists and has content
    if [ -s "$file" ]; then
        echo -e "${GREEN}PASS${NC} - File exists and has content"
        return 0
    else
        echo -e "${RED}FAIL${NC} - File is empty"
        return 1
    fi
}

# Test standalone examples
echo "Testing Standalone Examples:"
echo "----------------------------"

test_example "standalone/01_hello.he3" "Hello World"
test_example "standalone/02_calculator.he3" "Calculator"
test_example "standalone/03_security_events.he3" "Security & Events"

echo ""

# Test project examples
echo "Testing Project Examples:"
echo "------------------------"

test_example "projects/01_hello_project/he3project.json" "Hello Project Config"
test_example "projects/01_hello_project/src/main.he3" "Hello Project Main"
test_example "projects/01_hello_project/src/utils.he3" "Hello Project Utils"
test_example "projects/01_hello_project/README.md" "Hello Project README"

echo ""

# Summary
echo "Test Summary:"
echo "============="
echo "All example files have been created and verified."
echo ""
echo "Next steps:"
echo "1. Complete the He³ compiler implementation"
echo "2. Test compilation of these examples"
echo "3. Run the generated bytecode in the VM"
echo ""
echo "Example usage (when compiler is ready):"
echo "  he3 compile examples/standalone/01_hello.he3"
echo "  he3vm examples/standalone/01_hello.bx"
echo ""
echo "Project compilation (when ready):"
echo "  cd examples/projects/01_hello_project"
echo "  he3 build"
echo "  he3vm build/hello-project.bx"
