# GitHub Pages Configuration for He³ Documentation

title: He³ (Helium-3) Programming Language
description: A modern, object-oriented programming language with Pascal roots and Java/C#-style syntax
author: He³ Development Team
email: mootwise-matt@github.com

# GitHub repository
github:
  username: mootwise-matt
  repository: he3-lang

# Site settings
baseurl: "/he3-lang"
url: "https://mootwise-matt.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata

# Collections
collections:
  language:
    output: true
    permalink: /:collection/:name/
  compiler:
    output: true
    permalink: /:collection/:name/
  vm:
    output: true
    permalink: /:collection/:name/
  bytecode:
    output: true
    permalink: /:collection/:name/
  exporter:
    output: true
    permalink: /:collection/:name/
  development:
    output: true
    permalink: /:collection/:name/