# He³ (Helium-3) Programming Language Documentation
# Jekyll configuration for GitHub Pages

# Site settings
title: "He³ (Helium-3) Programming Language"
description: "A modern, object-oriented programming language with Pascal roots and Java/C#-style syntax"
url: "https://mootwise-matt.github.io"
baseurl: "/he3-lang"

# GitHub Pages settings
github: [metadata]
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Collections
collections:
  language:
    output: true
    permalink: /:collection/:name/
  compiler:
    output: true
    permalink: /:collection/:name/
  vm:
    output: true
    permalink: /:collection/:name/
  bytecode:
    output: true
    permalink: /:collection/:name/
  exporter:
    output: true
    permalink: /:collection/:name/
  development:
    output: true
    permalink: /:collection/:name/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "language"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "compiler"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "vm"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "bytecode"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "exporter"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "development"
    values:
      layout: "page"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - test.md
  - index_simple.md